try(require("shiny")||install.packages("shiny"))
try(require("nFactors")||install.packages("udpipe"))
try(require("shiny")||install.packages("textcat"))
try(require("shiny")||install.packages("dplyr"))
try(require("shiny")||install.packages("stringr"))
try(require("ggplot2")||install.packages("ggrapg"))

library("shiny")
library("udpipe")
library("textcat")
library("dplyr")
library("stringr")
library('gggraph')
